name: Bug report
description: 🐞 🐞 🐞 🐞 🐞
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Do you want this issue prioritized?
    description: If this issue is urgent, you can add prioritize it via a <a href="https://github.com/sponsors/nandorojo?frequency=one-time&sponsor=nandorojo">sponsorship on GitHub</a>. Feel free to tag @nandorojo here in the issue description if you sponsor.
    options:
    - label: Yes, I have sponsored
    - label: Not urgent
- type: textarea
  attributes:
    label: Current Behavior
    description: Describe what's happening in 1-2 sentences.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Add a MotiView component...
      2. Change to Animated.View...
  validations:
    required: false
- type: textarea
  attributes:
    label: Versions
    description: |
      examples:
        - **Moti**: 0.18.0
        - **Reanimated**: 2.5.0
        - **React Native**: 0.68.0
    value: |
        - Moti:
        - Reanimated:
        - React Native:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: |
      Please add screenshots / videos that show the behavior if applicable.
  validations:
    required: false
- type: textarea
  attributes:
    label: Reproduction
    description: |
      Please add a link to an Expo Snack or a **minimal reproduction**.

      If you can reproduce on Web, the easiest way to share a reproduction is by <a href="https://stackblitz.com/edit/nextjs-v5vkju?file=pages%2Findex.tsx">forking the StackBlitz starter</a>.
      
      If the issue only happens on native, you can use the starter app:
      
      ```sh
      npx create-react-native-app -t with-moti
      ```
  validations:
    required: true
